### Hi there 

:) I'm currently working on ...
I'm currently learning ...
I'm looking to colaborate on ...
I'm looking for help with ...
Ask me about ...
How to reach me: ...
Pronouns ...
fun facts ...
